name: Run JMeter Load Test

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run JMeter Test using PerfAction
      - name: Run JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ./demo_api_test.jmx
          args: '-n -t ./demo_api_test.jmx -l result.jtl -e -o reports/html'

      # Upload JMeter Report as an Artifact
      - name: Upload JMeter Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: reports/html
          retention-days: 7
